version: '3.4'

services:
  zhetistik:
    image: zhetistik
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    depends_on: 
      - migrations
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    environment:
      SA_PASSWORD: "rendermancentiao8*"
      ACCEPT_EULA: "Y"
    ports:
    - "14331:1433"
    depends_on: 
      - migrations
  migrations:
    build: 
      context: .
      dockerfile: Migrations.Dockerfile